const checklistData = [
  {
    id: 1,
    strategy: "New Concept Development",
    description: "Rethink the product concept to minimise environmental impact throughout the lifecycle.",
    color: "#2E7D32",
    items: [
      { id: "1.1", text: "Dematerialisation — can the product be replaced by a service?" },
      { id: "1.2", text: "Shared use or multi-functionality of the product" },
      { id: "1.3", text: "Integration of functions with other products" },
      { id: "1.4", text: "Functional optimisation of product components" },
      { id: "1.5", text: "Alternative scenarios to fulfil the same function with less environmental impact" },
      { id: "1.6", text: "New product concept that reduces resource consumption" },
      { id: "1.7", text: "Product–service system approach considered" },
    ],
  },
  {
    id: 2,
    strategy: "Selection of Low-Impact Materials",
    description: "Choose materials with the lowest possible environmental impact.",
    color: "#1565C0",
    items: [
      { id: "2.1", text: "Non-hazardous materials used (avoid toxic, carcinogenic, or ozone-depleting substances)" },
      { id: "2.2", text: "Non-exhaustible or renewable materials preferred" },
      { id: "2.3", text: "Low energy-content materials selected" },
      { id: "2.4", text: "Recycled materials used where possible" },
      { id: "2.5", text: "Recyclable materials selected" },
      { id: "2.6", text: "Materials selected for durability and reliability" },
      { id: "2.7", text: "Bio-based or biodegradable materials considered" },
    ],
  },
  {
    id: 3,
    strategy: "Reduction of Materials Usage",
    description: "Minimise the total weight and volume of materials in the product.",
    color: "#6A1B9A",
    items: [
      { id: "3.1", text: "Reduction in weight of the product" },
      { id: "3.2", text: "Reduction in volume of the product" },
      { id: "3.3", text: "Reduction in the number of different materials" },
      { id: "3.4", text: "Reduction in the number of components" },
      { id: "3.5", text: "Miniaturisation or compacting where functionally appropriate" },
      { id: "3.6", text: "Avoidance of over-dimensioning" },
      { id: "3.7", text: "Thinner walls / lighter structures without compromising function" },
    ],
  },
  {
    id: 4,
    strategy: "Optimisation of Production Techniques",
    description: "Use cleaner and more efficient production processes.",
    color: "#E65100",
    items: [
      { id: "4.1", text: "Use of cleaner production technologies" },
      { id: "4.2", text: "Fewer production steps required" },
      { id: "4.3", text: "Lower energy consumption in production" },
      { id: "4.4", text: "Less production waste generated" },
      { id: "4.5", text: "Fewer and cleaner production consumables (lubricants, solvents)" },
      { id: "4.6", text: "Reduced use of hazardous auxiliaries" },
      { id: "4.7", text: "Production waste can be reused or recycled" },
    ],
  },
  {
    id: 5,
    strategy: "Optimisation of Distribution System",
    description: "Minimise environmental impact in packaging, transport, and logistics.",
    color: "#00838F",
    items: [
      { id: "5.1", text: "Less, cleaner, or reusable packaging" },
      { id: "5.2", text: "Energy-efficient transport mode selected" },
      { id: "5.3", text: "Energy-efficient logistics (route optimisation, load maximisation)" },
      { id: "5.4", text: "Local sourcing to reduce transport distances" },
      { id: "5.5", text: "Packaging materials are recyclable or biodegradable" },
      { id: "5.6", text: "Product designed for compact or flat-pack shipping" },
      { id: "5.7", text: "Digital distribution considered where applicable" },
    ],
  },
  {
    id: 6,
    strategy: "Reduction of Impact During Use",
    description: "Minimise energy and resource consumption during the product's use phase.",
    color: "#C62828",
    items: [
      { id: "6.1", text: "Low energy consumption during use" },
      { id: "6.2", text: "Use of clean or renewable energy sources" },
      { id: "6.3", text: "Fewer consumables needed during use" },
      { id: "6.4", text: "Consumables used are clean and renewable" },
      { id: "6.5", text: "No waste or emissions during use" },
      { id: "6.6", text: "Reduced water consumption during use" },
      { id: "6.7", text: "Energy-saving modes or auto-off features included" },
    ],
  },
  {
    id: 7,
    strategy: "Optimisation of Initial Lifetime",
    description: "Extend the product's useful life to reduce replacement frequency.",
    color: "#4527A0",
    items: [
      { id: "7.1", text: "High reliability and durability designed in" },
      { id: "7.2", text: "Easy maintenance and repair by the user" },
      { id: "7.3", text: "Modular product structure for component replacement" },
      { id: "7.4", text: "Classic design and aesthetics (avoid fashion-driven obsolescence)" },
      { id: "7.5", text: "Strong product–user relationship to discourage disposal" },
      { id: "7.6", text: "Upgradability or adaptability designed in" },
      { id: "7.7", text: "Spare parts availability planned" },
    ],
  },
  {
    id: 8,
    strategy: "Optimisation of End-of-Life System",
    description: "Design for reuse, remanufacturing, recycling, or safe disposal.",
    color: "#37474F",
    items: [
      { id: "8.1", text: "Reuse of the product as a whole" },
      { id: "8.2", text: "Remanufacturing or refurbishment of the product" },
      { id: "8.3", text: "Recycling of materials" },
      { id: "8.4", text: "Safe incineration with energy recovery" },
      { id: "8.5", text: "Easy disassembly and separation of materials" },
      { id: "8.6", text: "Material identification and marking on components" },
      { id: "8.7", text: "Safe disposal of non-recyclable residues" },
    ],
  },
];

export default checklistData;
